version: "3.9"
services:
    nginx:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "8081:80"
        env_file: .env
        depends_on:
            - php-fpm
        volumes:
            - ./:/app

    php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        env_file: .env
        volumes:
            - ./:/app

    php-cli:
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        env_file: .env
        volumes:
            - ./:/app

    mysql:
        image: mysql/mysql-server:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:

