version: "3.9"
services:
    nginx:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        env_file: .env
        volumes:
            - ./:/app

    php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        env_file: .env
        volumes:
            - ./:/app

    php-cli:
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        env_file: .env
        volumes:
            - ./:/app

    mysql:
        image: mysql/mysql-server:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: app
            MYSQL_USER: root
            MYSQL_PASSWORD: app
            MYSQL_DATABASE: app
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:

